// SPDX-License-Identifier: Apache-2.0
//! /etc/hosts injection builder (Ruling E, v1 static).
//!
//! Builds /etc/hosts content for workload name resolution. The agent generates
//! a static /etc/hosts file that maps dummy IPs to canonical service hostnames.
//!
//! The canonical hostname format is defined by `fleetos_core::naming::dummy_ip_hostname`:
//!   `{service}.{role}.{tenant}.svc.{trust_domain}`
//!
//! This content is:
//! - Mounted into containerd containers via OCI-spec mount
//! - Passed to fleetos-guest-init via WorkloadConfig for MicroVMs
//!
//! Ruling E v1: static /etc/hosts injection. No dynamic DNS resolution.
//! The naming convention is owned by fleetos-core; this module only formats.

use crate::error::AgentError;
use fleetos_core::naming::dummy_ip_hostname;
use fleetos_core::proto::state::RouteEntry;
use fleetos_core::spiffe::SpiffeId;
use std::net::Ipv4Addr;

/// A single /etc/hosts entry: IP → hostname mapping.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HostsEntry {
    /// The dummy IP address in dotted-quad notation.
    pub ip: String,
    /// The canonical hostname for this service.
    pub hostname: String,
}

/// Build /etc/hosts entries from a set of route entries.
///
/// For each route entry, computes the canonical hostname using
/// `fleetos_core::naming::dummy_ip_hostname` and formats the IP
/// in dotted-quad notation.
///
/// `trust_domain` is the cluster's trust domain (from agent config).
pub fn build_hosts_entries(
    routes: &[RouteEntry],
    trust_domain: &str,
) -> Result<Vec<HostsEntry>, AgentError> {
    let mut entries = Vec::with_capacity(routes.len());

    for route in routes {
        // Parse the destination SpiffeId to extract tenant and service name.
        let dst_spiffe: SpiffeId = route.destination_svid.parse().map_err(|e| {
            AgentError::Policy(format!(
                "invalid destination_svid '{}': {}",
                route.destination_svid, e
            ))
        })?;

        // The service name is the SpiffeId's `name` field.
        let service_name = &dst_spiffe.name;
        // The tenant is the SpiffeId's `tenant` field.
        let tenant = &dst_spiffe.tenant;
        // The role comes from the route entry.
        let role = &route.destination_role;

        // Skip entries with empty role (wildcard routes don't get /etc/hosts entries).
        if role.is_empty() {
            continue;
        }

        // Compute the canonical hostname.
        let hostname =
            dummy_ip_hostname(service_name, role, tenant, trust_domain).map_err(|e| {
                AgentError::Policy(format!(
                    "failed to compute hostname for {}.{}.{}: {}",
                    service_name, role, tenant, e
                ))
            })?;

        // Convert the canonical IPv4 value to dotted-quad notation.
        let ip = Ipv4Addr::from(route.dummy_ip);
        let ip_str = ip.to_string();

        entries.push(HostsEntry {
            ip: ip_str,
            hostname,
        });
    }

    Ok(entries)
}

/// Format the complete /etc/hosts file content from a set of entries.
///
/// Includes a header comment and the standard localhost entries,
/// followed by the FleetOS service entries.
pub fn format_hosts_file(entries: &[HostsEntry]) -> String {
    let mut content = String::new();

    // Standard header.
    content.push_str("# /etc/hosts — generated by fleetos-agent\n");
    content.push_str("# Do not edit. This file is regenerated on route updates.\n");
    content.push_str("#\n");

    // Standard localhost entries.
    content.push_str("127.0.0.1\tlocalhost\n");
    content.push_str("::1\tlocalhost ip6-localhost ip6-loopback\n");
    content.push_str("\n");

    // FleetOS service entries.
    if !entries.is_empty() {
        content.push_str("# FleetOS service resolution (Ruling E)\n");
        for entry in entries {
            content.push_str(&format!("{}\t{}\n", entry.ip, entry.hostname));
        }
    }

    content
}

/// Build the complete /etc/hosts content from route entries.
///
/// Convenience function combining `build_hosts_entries` and `format_hosts_file`.
pub fn build_hosts_content(
    routes: &[RouteEntry],
    trust_domain: &str,
) -> Result<String, AgentError> {
    let entries = build_hosts_entries(routes, trust_domain)?;
    Ok(format_hosts_file(&entries))
}
