// SPDX-License-Identifier: Apache-2.0
//! WorkloadConfig construction and push.
//!
//! After attestation passes, the agent constructs a `WorkloadConfig` and
//! pushes it to the guest over the VSOCK stream. The config contains:
//!   - SVID cert chain + private key (agent-generated keypair)
//!   - Environment variables
//!   - Volume mounts
//!   - Dummy-IP routes (from routes/table.rs)
//!   - Workload binary path, args
//!   - Trust domain, tenant, service, role
//!   - Guest networking (IP, netmask, gateway)
//!
//! The SVID generation depends on the join flow (Batch 9) and delegated
//! signing (Batch 8). For now, the builder structure is in place with
//! TODOs for the parts that depend on later batches.

use fleetos_core::vsock_proto::{DummyIpRouteConfig, VolumeMountConfig, WorkloadConfig};

use crate::error::AgentError;

use super::WorkloadContext;
use super::verify::VerifiedGuest;

/// Builder for `WorkloadConfig`.
///
/// Holds the agent state needed to construct configs. The actual SVID
/// generation is a TODO pending Batch 8 (delegated signing) and Batch 9
/// (join flow).
pub struct WorkloadConfigBuilder {
    trust_domain: String,
    dummy_ip_routes: std::sync::RwLock<Vec<DummyIpRouteConfig>>,
}

impl WorkloadConfigBuilder {
    pub fn new(trust_domain: String) -> Self {
        Self {
            trust_domain,
            dummy_ip_routes: std::sync::RwLock::new(Vec::new()),
        }
    }

    /// Set the dummy-IP routes (driven by WatchRoutes). Takes &self for Arc use.
    pub fn set_dummy_ip_routes(&self, routes: Vec<DummyIpRouteConfig>) {
        *self.dummy_ip_routes.write().unwrap() = routes;
    }

    /// Build a `WorkloadConfig` for a verified guest using the workload context.
    ///
    /// TODO(Batch 8/9): Generate the workload SVID using the agent's
    /// delegated signing key or the control CA. For now, this returns a
    /// config with empty SVID fields.
    pub fn build(
        &self,
        _guest: &VerifiedGuest,
        ctx: &WorkloadContext,
    ) -> Result<WorkloadConfig, AgentError> {
        // TODO(Batch 8/9): Generate workload SVID.
        // The SVID cert chain and private key are generated by the agent
        // and sealed to the guest's X25519 pubkey. For now, return empty.
        let svid_cert_chain_der = Vec::new();
        let svid_private_key_der = Vec::new();

        // Populate env vars from PodSpec
        let env_vars = ctx
            .pod_spec
            .env
            .iter()
            .map(|e| (e.name.clone(), e.value.clone()))
            .collect();

        // Populate volume mounts from PodSpec
        let volume_mounts = ctx
            .pod_spec
            .volume_mounts
            .iter()
            .map(|vm| VolumeMountConfig {
                name: vm.name.clone(),
                mount_path: vm.mount_path.clone(),
                read_only: vm.read_only,
            })
            .collect();

        // Workload binary path and args are not directly in PodSpec.
        // For now, derive from workload_id or use defaults.
        // In a real implementation, this would be resolved from the image manifest.
        let workload_binary_path = format!("/usr/bin/{}", ctx.pod_spec.workload_id);
        let workload_args = Vec::new(); // TODO: extract from PodSpec if needed

        Ok(WorkloadConfig {
            svid_cert_chain_der,
            svid_private_key_der,
            env_vars,
            volume_mounts,
            dummy_ip_routes: self.dummy_ip_routes.read().unwrap().clone(),
            workload_binary_path,
            workload_args,
            trust_domain: self.trust_domain.clone(),
            tenant_id: ctx.pod_spec.tenant_id.clone(),
            service_name: ctx.pod_spec.workload_id.clone(),
            role: ctx.pod_spec.role.clone(),
            guest_ip: ctx.guest_ip,
            netmask: ctx.netmask,
            gateway: ctx.gateway,
        })
    }

    /// Fallback build when no workload context is available (e.g., test/dev).
    pub fn build_fallback(&self, _guest: &VerifiedGuest) -> Result<WorkloadConfig, AgentError> {
        let svid_cert_chain_der = Vec::new();
        let svid_private_key_der = Vec::new();

        Ok(WorkloadConfig {
            svid_cert_chain_der,
            svid_private_key_der,
            env_vars: Vec::new(),
            volume_mounts: Vec::new(),
            dummy_ip_routes: self.dummy_ip_routes.read().unwrap().clone(),
            workload_binary_path: String::new(),
            workload_args: Vec::new(),
            trust_domain: self.trust_domain.clone(),
            tenant_id: String::new(),
            service_name: String::new(),
            role: String::new(),
            guest_ip: [0, 0, 0, 0],
            netmask: [0, 0, 0, 0],
            gateway: [0, 0, 0, 0],
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use fleetos_core::proto::fleetos::{EnvVar, VolumeMount};

    #[test]
    fn config_push_populates_fields_from_context() {
        let builder = WorkloadConfigBuilder::new("fleet.example.internal".to_string());
        builder.set_dummy_ip_routes(vec![DummyIpRouteConfig {
            dummy_ip: [240, 0, 0, 45],
            service: "db".to_string(),
            role: "replica".to_string(),
            tenant: "acme".to_string(),
        }]);

        let guest = VerifiedGuest {
            guest_x25519_pubkey: [0x11; 32],
        };

        let ctx = WorkloadContext {
            pod_spec: fleetos_core::proto::fleetos::PodSpec {
                tenant_id: "acme".to_string(),
                workload_id: "db".to_string(),
                role: "primary".to_string(),
                env: vec![EnvVar {
                    name: "FOO".to_string(),
                    value: "bar".to_string(),
                }],
                volume_mounts: vec![VolumeMount {
                    name: "scratch".to_string(),
                    mount_path: "/scratch".to_string(),
                    read_only: false,
                }],
                ..Default::default()
            },
            guest_ip: [10, 0, 0, 2],
            netmask: [255, 255, 255, 0],
            gateway: [10, 0, 0, 1],
        };

        let config = builder.build(&guest, &ctx).unwrap();

        assert_eq!(config.trust_domain, "fleet.example.internal");
        assert_eq!(config.tenant_id, "acme");
        assert_eq!(config.service_name, "db");
        assert_eq!(config.role, "primary");
        assert_eq!(config.guest_ip, [10, 0, 0, 2]);
        assert_eq!(config.netmask, [255, 255, 255, 0]);
        assert_eq!(config.gateway, [10, 0, 0, 1]);
        assert_eq!(config.env_vars.len(), 1);
        assert_eq!(config.env_vars[0].0, "FOO");
        assert_eq!(config.volume_mounts.len(), 1);
        assert_eq!(config.volume_mounts[0].name, "scratch");
        assert_eq!(config.dummy_ip_routes.len(), 1);
        assert_eq!(config.dummy_ip_routes[0].dummy_ip, [240, 0, 0, 45]);
    }
}
