// SPDX-License-Identifier: Apache-2.0
//! WorkloadConfig construction and push.
//!
//! After attestation passes, the agent constructs a `WorkloadConfig` and
//! pushes it to the guest over the VSOCK stream. The config contains:
//!   - SVID cert chain + private key (agent-generated keypair)
//!   - Environment variables
//!   - Volume mounts
//!   - Dummy-IP routes (from routes/table.rs)
//!   - Workload binary path, args
//!   - Trust domain, tenant, service, role
//!   - Guest networking (IP, netmask, gateway)
//!
//! The SVID generation depends on the join flow (Batch 9) and delegated
//! signing (Batch 8). For now, the builder structure is in place with
//! TODOs for the parts that depend on later batches.

use fleetos_core::vsock_proto::{DummyIpRouteConfig, WorkloadConfig};

use crate::error::AgentError;

use super::verify::VerifiedGuest;

/// Builder for `WorkloadConfig`.
///
/// Holds the agent state needed to construct configs. The actual SVID
/// generation is a TODO pending Batch 8 (delegated signing) and Batch 9
/// (join flow).
pub struct WorkloadConfigBuilder {
    /// The trust domain for this cluster.
    trust_domain: String,
    /// Dummy-IP routes to include in the config.
    /// Populated from routes/table.rs (Batch 6).
    dummy_ip_routes: Vec<DummyIpRouteConfig>,
}

impl WorkloadConfigBuilder {
    pub fn new(trust_domain: String) -> Self {
        Self {
            trust_domain,
            dummy_ip_routes: Vec::new(),
        }
    }

    /// Set the dummy-IP routes to include in workload configs.
    pub fn set_dummy_ip_routes(&mut self, routes: Vec<DummyIpRouteConfig>) {
        self.dummy_ip_routes = routes;
    }

    /// Build a `WorkloadConfig` for a verified guest.
    ///
    /// TODO(Batch 8/9): Generate the workload SVID using the agent's
    /// delegated signing key or the control CA. For now, this returns a
    /// config with empty SVID fields.
    pub fn build(&self, _guest: &VerifiedGuest) -> Result<WorkloadConfig, AgentError> {
        // TODO(Batch 8/9): Generate workload SVID.
        // The SVID cert chain and private key are generated by the agent
        // and sealed to the guest's X25519 pubkey. For now, return empty.
        let svid_cert_chain_der = Vec::new();
        let svid_private_key_der = Vec::new();

        Ok(WorkloadConfig {
            svid_cert_chain_der,
            svid_private_key_der,
            env_vars: Vec::new(),
            volume_mounts: Vec::new(),
            dummy_ip_routes: self.dummy_ip_routes.clone(),
            workload_binary_path: String::new(),
            workload_args: Vec::new(),
            trust_domain: self.trust_domain.clone(),
            tenant_id: String::new(),
            service_name: String::new(),
            role: String::new(),
            guest_ip: [0, 0, 0, 0],
            netmask: [0, 0, 0, 0],
            gateway: [0, 0, 0, 0],
        })
    }
}
