// SPDX-License-Identifier: Apache-2.0
//! Environment variable injection and /etc/hosts generation.
//!
//! Ruling E: /etc/hosts injection for service-name resolution.
//! The canonical hostname convention is owned by `fleetos_core::naming::dummy_ip_hostname`.

use fleetos_core::proto::workload::EnvVar;

/// Build environment variables for a workload.
pub fn build_env(env_vars: &[EnvVar]) -> Vec<(String, String)> {
    env_vars
        .iter()
        .map(|e| (e.name.clone(), e.value.clone()))
        .collect()
}

/// Generate /etc/hosts entries from dummy IP routes.
///
/// Uses `fleetos_core::naming::dummy_ip_hostname` — the canonical hostname
/// convention owned by fleetos-core. Never re-implement this.
pub fn generate_hosts_entries(
    routes: &[fleetos_core::proto::state::RouteEntry],
    trust_domain: &str,
) -> Vec<(String, String)> {
    let mut entries = Vec::new();

    for route in routes {
        let hostname = fleetos_core::naming::dummy_ip_hostname(
            &route.destination_svid,
            &route.destination_role,
            trust_domain,
            trust_domain,
        )
        .unwrap_or_else(|_| route.destination_svid.clone());

        let ip = std::net::Ipv4Addr::from(route.dummy_ip);
        entries.push((ip.to_string(), hostname));
    }

    entries
}

/// Format /etc/hosts content.
pub fn format_hosts(entries: &[(String, String)]) -> String {
    let mut content = String::new();
    content.push_str("# Generated by fleetos-agent\n");
    content.push_str("127.0.0.1\tlocalhost\n");

    for (ip, hostname) in entries {
        content.push_str(&format!("{}\t{}\n", ip, hostname));
    }

    content
}
